es.logger.level: INFO
rootLogger: ${es.logger.level}, console
logger:
#  action: DEBUG
  cluster.routing.allocation: WARN
  cluster.metadata: WARN

appender:
  console:
    type: console
    layout:
      type: consolePattern
      conversionPattern: "[ElasticSearch][%p][%c] %m%n"
